### ISSUE TITLE
Catch RedisException in \Laminas\Cache\Storage\Adapter\RedisResourceManager::connect

### ISSUE THREAD

**Issue by michaltyszczenko** [laminas/laminas-cache-storage-adapter-redis#22]
Connect to redis in \Laminas\Cache\Storage\Adapter\RedisResourceManager::connect should be in try/catch.
Redis throw RedisException. Example:

```
 try {
   $success = $redis->connect($server['host'], $server['port'],   ##$server['timeout']);
} catch (\RedisException $e) {
  $success = false;
}
```

**Comment by froschdesign** [comment]
> Connect to redis in \Laminas\Cache\Storage\Adapter\RedisResourceManager::connect

This part:

https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/c147cee8a0e1fdb08ac2474572e34ca5de81dbaf/src/RedisResourceManager.php#L282-L312

**Comment by michaltyszczenko** [comment]
The same situation is in the \Laminas\Cache\Storage\Adapter\RedisResourceManager::getResource when get redis info. Redis throw RedisException.


(https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/c147cee8a0e1fdb08ac2474572e34ca5de81dbaf/src/RedisResourceManager.php#L157-L164)

**Comment by froschdesign** [comment]
@michaltyszczenko 
Can you create a pull request that solves the problem?

**Comment by boesing** [comment]
I've created a patch for this. Sorry that this went under the radar, I usually do not work with `Redis` (but with `RedisCluster`)  and therefore I did not experienced any issues.

Since this changes the way how the current `Redis` adapter works, the patch will land in the next major version.
