### ISSUE TITLE
Usage of Interop\Container\ContainerInterface in AdapterPluginManagerDelegatorFactory precludes the use of PSR containers

### ISSUE THREAD

**Issue by cooperaj** [laminas/laminas-cache-storage-adapter-redis#24]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes

#### Summary

By using `Interop\Container\ContainerInterface` (which merely extends the PSR11 ContainerInterface) the usage of PSR11 containers such as `elie29/zend-di-config` is not possible. 

If the AdapterPluginManagerDelegatorFactory class were to use \Psr\Container\Container interface it would work for all implementations.

**Comment by boesing** [comment]
Good catch! Sadly, this would be actually a BC break. I obviously failed there and probably in almost all other adapter we do actually support...

I think we can create a new major for this. Thats one of the benefits of extracting the adapters out from `laminas-cache`.
Would you mind preparing a PR? I will create a 3.x branch afterwards and retarget the PR.
We should think about marking the delegator factory `@internal`.
