### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by FabianKoestring** [laminas/laminas-cache-storage-adapter-redis#60]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary
Make this laminas/cache Adapter compatible with new php 8.2 release.

**Comment by Ocramius** [comment]
Duplicates #58

**Comment by FabianKoestring** [comment]
Sorry, did not see that. 🤷‍♂️

**Comment by Ocramius** [comment]
No worries, just doing housekeeping 😁
