### ISSUE TITLE
Change from protected to public visibility method getRedisResource in Redis class.

### ISSUE THREAD

**Issue by vkywalker** [laminas/laminas-cache-storage-adapter-redis#73]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

It makes no sense that final class Redis has protected methods on it. 
The difference between private and protected visibility is that child classes can see and use protected members, but they cannot see private ones. Since a final class will have no children, marking the members of a final class protected is pointless.

**Comment by froschdesign** [comment]
@vkywalker 
If the method is for internal use only, there is no need to open the API of the class.

But if you need the redis resource, why not use the options:

https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/1e2f612a634f35a95886ee4b66affd7d29fe1227/src/Redis.php#L113-L126

https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/1e2f612a634f35a95886ee4b66affd7d29fe1227/src/RedisOptions.php#L105-L116

https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/1e2f612a634f35a95886ee4b66affd7d29fe1227/src/RedisOptions.php#L118-L126

**Comment by vkywalker** [comment]
@froschdesign  Thank you Frank,  yes I get resource from options, I was pointed out that It makes no sense to have protected method on final class.  That is all!

**Comment by froschdesign** [comment]
@vkywalker 
> I was pointed out that It makes no sense to have protected method on final class. That is all!

Then I must have misunderstood the title of this issue report:

> Change from protected to public visibility method getRedisResource in Redis class.

**Comment by vkywalker** [comment]
@froschdesign  Yes Frank, I suggested set it to public, but It can be private as well.  I have just pointed out that having protected visibility in final class is confusing. Great job.

**Comment by froschdesign** [comment]
Maybe simply overlooked: https://github.com/laminas/laminas-cache-storage-adapter-redis/pull/21
So no bigger problem and can be changed. But I would leave it up to @boesing (the maintainer of laminas-cache) to open the API of the class or not.

**Comment by boesing** [comment]
Happy to see a PR to have it `private`. 
Pretty sure I just marked the class `final` with v2 without modifying the `protected` stuff. 
Prior v2, the class was not `final`.
I have no plans to change this as of now and pretty sure won't spent time on this in the next years unless I stumble over it. There is no real need to change that and thus, I definitely want to spend my time on other stuff. However, I'd be open to merge these changes in a minor release.

**Comment by boesing** [comment]
Closing here as I've changed visibiltiy to `private` in v3.0.0, it was just protected due to the fact that in v2 the class was marked `final` while the visibility of other methods remained.
