### ISSUE TITLE
mget within RedisCluster now also returns false

### ISSUE THREAD

**Issue by CyberLine** [laminas/laminas-cache-storage-adapter-redis#74]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.5.0

#### Summary

`mget` within RedisCluster now also returns `false` on errors:
https://github.com/phpredis/phpredis/blob/35a7cc094c6c264aa37738b074c4c54c4ca73b87/redis_cluster.c#L694

#### Current behavior

message `foreach() argument must be of type array|object, bool given` thrown on line 202 of `vendor/laminas/laminas-cache-storage-adapter-redis/src/RedisCluster.php`

#### Expected behavior

An exception should be thrown

**Comment by boesing** [comment]
Can confirm that phpredis can return [non-array](https://github.com/phpredis/phpredis/blob/35a7cc094c6c264aa37738b074c4c54c4ca73b87/redis_cluster.stub.php#L621C3-L621C3) return values and thus checking for the return value should work.
