### ISSUE TITLE
PHP 8.3 support 

### ISSUE THREAD

**Issue by FabianKoestring** [laminas/laminas-cache-storage-adapter-redis#81]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary
Make this laminas/cache Adapter compatible with new php 8.3 release.

**Comment by boesing** [comment]
PR welcome.

**Comment by FabianKoestring** [comment]
> PR welcome.

@boesing Seems like boesing/psalm-plugin-stringf must be updated first. 🤷‍♂️

**Comment by froschdesign** [comment]
Fixed with #83 and released with version [2.7.0](https://github.com/laminas/laminas-cache-storage-adapter-redis/releases/tag/2.7.0).
